branches:
  only:
    - master
    - dev

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed aobuya/udagram-api-feed:v1
  - docker tag udagram-api-user aobuya/udagram-api-user:v1
  - docker tag udagram-frontend aobuya/udagram-frontend:v1
  - docker tag udagram-reverseproxy aobuya/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push aobuya/udagram-api-feed:v1
  - docker push aobuya/udagram-api-user:v1
  - docker push aobuya/udagram-frontend:v1
  - docker push aobuya/udagram-reverseproxy:v1
